export const ROLE_LEVELS: Record<string, number> = {
  SUPER_ADMIN: 5,
  TENANT_ADMIN: 4,
  RESPONSIBLE_PHARMACIST: 4,
  FACILITY_MANAGER: 3,
  PROCESSING_MANAGER: 3,
  PROCESSING_SUPERVISOR: 2,
  FACILITY_SUPERVISOR: 3,
  QA_INSPECTOR: 3,
  CULTIVATOR: 2,
  LAB_TECH: 2,
  IRRIGATION_TECH: 2,
  MAINTENANCE_MANAGER: 3,
  HEAD_OF_CULTIVATION: 3,
  NURSERY_MANAGER: 3,
  DELIVERY_DRIVER: 1,
  SECURITY_OFFICER: 1,
  TRIMMER: 1,
  GENERAL_WORKER: 1,
  HOUSEKEEPING: 1,
  LAUNDRY: 1,
  CLIENT: 0,
  VIEWER: 0,
};

export const WEIGHT_VARIANCE_THRESHOLDS: Record<string, number> = {
  BIN: 0.05,
  BAG: 0.05,
  JAR: 0.05,
  RACK: 0.15,
  PACKAGE: 0.05,
  CUSTOM: 0.10,
};

export const PLANT_PHASE_ORDER = [
  'SEEDLING', 'VEGETATIVE', 'FLOWERING', 'HARVESTED',
  'DRYING', 'CURING', 'PROCESSING', 'PACKAGED',
] as const;
