// Day-End Z-Report generator — PDF (pdfkit) + CSV
const PDFDocument = require('pdfkit');

function rand(v) { return 'R' + (Number(v) || 0).toFixed(2); }

function buildCsv(session, sales) {
  const rows = [['Slip', 'Date/Time', 'Items', 'Payment', 'Subtotal', 'VAT', 'Total', 'Status']];
  for (const s of sales) {
    const items = (s.items || []).reduce((a, i) => a + (i.quantity || 0), 0);
    const subtotal = s.subtotal != null ? s.subtotal : (s.totalAmount || 0);
    const vat = s.taxAmount != null ? s.taxAmount : ((s.totalAmount || 0) - subtotal);
    rows.push([
      s.saleNumber || '', new Date(s.createdAt).toLocaleString('en-ZA'),
      items, (s.paymentMethod || (s.payments && s.payments[0] && s.payments[0].method) || '').toUpperCase(),
      subtotal.toFixed(2), (vat || 0).toFixed(2), (s.totalAmount || 0).toFixed(2), s.status || ''
    ]);
  }
  return rows.map(r => r.map(c => '"' + String(c).replace(/"/g, '""') + '"').join(',')).join('\n');
}

function buildPdf(session, sales, branchName) {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ size: 'A4', margin: 50 });
    const chunks = [];
    doc.on('data', c => chunks.push(c));
    doc.on('end', () => resolve(Buffer.concat(chunks)));
    doc.on('error', reject);

    const when = new Date(session.closedAt || Date.now()).toLocaleString('en-ZA');
    doc.fontSize(22).fillColor('#C9A84C').text('ORIGIN by ILCO', { align: 'center' });
    doc.fontSize(14).fillColor('#111').text('Day-End Z-Report', { align: 'center' });
    doc.fontSize(10).fillColor('#555').text(`${branchName}   ·   ${when}`, { align: 'center' });
    if (session.sessionNumber) doc.fontSize(9).fillColor('#777').text(`Session ${session.sessionNumber}`, { align: 'center' });
    doc.moveDown(1);

    const row = (label, value, opts = {}) => {
      const y = doc.y;
      doc.fontSize(opts.big ? 13 : 11).fillColor(opts.big ? '#111' : '#333').text(label, 60, y);
      doc.fontSize(opts.big ? 13 : 11).fillColor(opts.big ? '#C9A84C' : '#111')
        .text(value, 60, y, { align: 'right', width: doc.page.width - 120 });
      doc.moveDown(0.4);
    };

    doc.fontSize(12).fillColor('#111').text('Takings by Payment Type', 60); doc.moveDown(0.3);
    row('Cash', rand(session.totalCash));
    row('Card (Speedpoint)', rand(session.totalCard));
    row('Manual EFT', rand(session.totalEFT));
    if (session.totalInstapay) row('Instapay', rand(session.totalInstapay));
    doc.moveTo(60, doc.y).lineTo(doc.page.width - 60, doc.y).strokeColor('#ddd').stroke(); doc.moveDown(0.4);
    row('TOTAL SALES', rand(session.totalSales), { big: true });
    doc.moveDown(0.6);

    doc.fontSize(12).fillColor('#111').text('Cash Reconciliation', 60); doc.moveDown(0.3);
    row('Opening Float', rand(session.openingFloat));
    row('Expected Cash', rand(session.expectedCash));
    row('Counted Cash', rand(session.actualCash));
    row('Variance', rand(session.variance));
    row('Transactions', String(session.transactionCount || sales.length));
    if (session.closingNotes) { doc.moveDown(0.3); doc.fontSize(10).fillColor('#555').text('Notes: ' + session.closingNotes, 60); }
    doc.moveDown(0.8);

    doc.fontSize(12).fillColor('#111').text('Transactions', 60); doc.moveDown(0.3);
    doc.fontSize(9).fillColor('#333');
    if (!sales.length) doc.text('No transactions.', 60);
    sales.forEach(s => {
      const t = new Date(s.createdAt).toLocaleTimeString('en-ZA', { hour: '2-digit', minute: '2-digit' });
      const tag = (s.status && s.status !== 'completed') ? '  [' + s.status.toUpperCase() + ']' : '';
      doc.fillColor(s.status === 'voided' || s.status === 'refunded' ? '#999' : '#333')
        .text(`#${s.saleNumber || '—'}   ${t}   ${(s.paymentMethod || (s.payments && s.payments[0] && s.payments[0].method) || '').toUpperCase()}   ${rand(s.totalAmount)}${tag}`, 60);
    });

    doc.moveDown(1.5);
    doc.fontSize(8).fillColor('#999').text('Generated by Origin Retail POS · ' + new Date().toLocaleString('en-ZA'), 60, doc.y, { align: 'center' });
    doc.end();
  });
}

module.exports = { buildCsv, buildPdf };
