import { Router } from 'express';
import authRoutes from './auth.routes';
import plantRoutes from './plant.routes';
import containerRoutes from './container.routes';
import batchRoutes from './batch.routes';
import labRoutes from './lab.routes';
import coaRoutes from './coa.routes';
import complianceRoutes from './compliance.routes';
import transportRoutes from './transport.routes';
import anomalyRoutes from './anomaly.routes';
import qmsRoutes from './qms.routes';
import worldModelRoutes from './worldModel.routes';
import notificationRoutes from './notification.routes';
import facilityRoutes from './facility.routes';
import auditRoutes from './audit.routes';
import scanRoutes from './scan.routes';
import onboardingRoutes from './onboarding.routes';
import qrRoutes from './qr.routes';
import documentRoutes from './documents.routes';
import usersRoutes from './users.routes';
import baygridRoutes from './baygrid.routes';
import tasksRoutes from './tasks.routes';
import assetsRoutes from './assets.routes';
import trimRoutes from './trim.routes';
import strainRoutes from './strain.routes';
import feedingRoutes from './feeding.routes';
import mortalityRoutes from './mortality.routes';
import cloneRoutes from './clone.routes';
import smfRoutes from './sitemasterfile.routes';
import shiftRoutes from './shift.routes';
import motherRoutes from './mother.routes';
import hrRoutes from './hr.routes';
import forecastRoutes from './forecast.routes';
import smartRoutes from './smart.routes';
import cultivationSopsRoutes from './cultivation-sops.routes';
import gmpRoutes from './gmp.routes';
import ghostAuditRoutes from './ghost-audit.routes';
import conciergeRoutes from './concierge.routes';
import chatRoutes from './chat.routes';
import labelRoutes from './labels.routes';
import originRoutes from './origin.routes';
import driverRoutes from './driver.routes';

const router = Router();

router.use('/auth', authRoutes);
router.use('/scan', scanRoutes);
router.use('/onboarding', onboardingRoutes);
router.use('/qr', qrRoutes);
router.use('/documents', documentRoutes);
router.use('/users', usersRoutes);
router.use('/baygrid', baygridRoutes);
router.use('/tasks', tasksRoutes);
router.use('/assets', assetsRoutes);
router.use('/trim', trimRoutes);
router.use('/strains', strainRoutes);
router.use('/feeding', feedingRoutes);
router.use('/mortality', mortalityRoutes);
router.use('/clones', cloneRoutes);
router.use('/site-master-file', smfRoutes);
router.use('/shifts', shiftRoutes);
router.use('/mothers', motherRoutes);
router.use('/hr', hrRoutes);
router.use('/forecast', forecastRoutes);
router.use('/smart', smartRoutes);
router.use('/plants', plantRoutes);
router.use('/containers', containerRoutes);
router.use('/batches', batchRoutes);
router.use('/lab', labRoutes);
router.use('/coa', coaRoutes);
router.use('/compliance', complianceRoutes);
router.use('/transport', transportRoutes);
router.use('/anomalies', anomalyRoutes);
router.use('/qms', qmsRoutes);
router.use('/world-model', worldModelRoutes);
router.use('/driver', driverRoutes);
router.use('/notifications', notificationRoutes);
router.use('/facilities', facilityRoutes);
router.use('/audit', auditRoutes);
router.use('/gmp', gmpRoutes);
router.use('/audit/ghost', ghostAuditRoutes);
router.use('/concierge', conciergeRoutes);
router.use('/chat', chatRoutes);
router.use('/labels', labelRoutes);
router.use('/origin', originRoutes);

router.get('/health', (_req, res) => {
  res.json({ status: 'ok', service: 'tnt-za', timestamp: new Date().toISOString() });
});

// Cultivation SOP surfaces — digitised paper SOPs (3-CUL / 8-CLN / 4-FAC)
router.use('/', cultivationSopsRoutes);

export default router;
